language: shell
os: linux
dist: bionic
env:
  global:
    - ANDROID_HOME=${HOME}/android
    - ANDROID_SDK_ROOT=${ANDROID_HOME}
    - TOOLS=${ANDROID_HOME}/cmdline-tools
    - PATH=${ANDROID_HOME}/emulator:${TOOLS}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
before_install:
  - mkdir -p ${ANDROID_HOME}/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ${ANDROID_HOME}/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ${ANDROID_HOME}/licenses/android-sdk-license
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> ${ANDROID_HOME}/licenses/android-sdk-license
install:
  - mkdir -p ${TOOLS}
  - travis_retry wget https://dl.google.com/android/repository/commandlinetools-linux-6514223_latest.zip -O ${TOOLS}/tools.zip
  - unzip ${TOOLS}/tools.zip -d ${TOOLS}
  - yes | travis_retry sdkmanager "platform-tools" > /dev/null
  - yes | travis_retry sdkmanager "tools" > /dev/null
  - yes | travis_retry sdkmanager "build-tools;30.0.1" > /dev/null
  - yes | travis_retry sdkmanager "platforms;android-30" > /dev/null
script:
  - ./gradlew assemble check
